//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreRandomDataGeneration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        public Toy()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Manufacturer { get; set; }
        public decimal Price { get; set; }
        public string Color { get; set; }
        public Nullable<int> AgeRange { get; set; }
    
        public virtual AgeRange AgeRange1 { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
