//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademyDBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int LogID { get; set; }
        public int LogDate { get; set; }
        public int WorkID { get; set; }
        public Nullable<int> OldEmployeeID { get; set; }
        public Nullable<System.DateTime> OldWorkDate { get; set; }
        public string OldTask { get; set; }
        public Nullable<int> OldWorkHours { get; set; }
        public Nullable<int> NewEmployeeID { get; set; }
        public Nullable<System.DateTime> NewWorkDate { get; set; }
        public string NewTask { get; set; }
        public Nullable<int> NewWorkHours { get; set; }
    
        public virtual WorkHour WorkHour { get; set; }
    }
}
